# Generated by Django 5.0 on 2024-01-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_attempt_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
