# Generated by Django 5.0 on 2024-01-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
