# Generated by Django 4.2 on 2024-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_delete_marketing"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="info",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
