# Generated by Django 4.2 on 2024-01-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_client_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="info",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
