# Generated by Django 4.2 on 2024-01-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="outbound_purpose",
            field=models.TextField(default="Default"),
        ),
    ]
