# Generated by Django 4.2 on 2024-01-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_chatbot_outbound_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="outbound_end",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
